name:                MaterialBalancer
version:             0.0.2.0
github:              "MiRiS-Project/MaterialBalancer"
license:             AllRightsReserved
author:              "MiRiS Project"
maintainer:          "developer@miris-project.net"
copyright:           "2019 MiRiS Project"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/MiRiS-Project/MaterialBalancer#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- text
- unordered-containers
- vector

library:
  source-dirs: src

default-extensions:
- OverloadedStrings
- RecordWildCards
# -BangPatterns
# -ViewPatterns
# -PatternSynonyms
# -TypeOperators

executables:
  MaterialBalancer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - MaterialBalancer

tests:
  MaterialBalancer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    default-extensions:
    - TemplateHaskell
    dependencies:
    - MaterialBalancer
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
